"""Declarative base and the conventions every model follows. See TICKET-004.

Plain-English: one base class that all tables inherit from, with a shared rule
for naming constraints (so migrations can be generated and reverted reliably)
and a mixin that gives every table an id and timestamps.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, Uuid, func, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# A naming convention is what lets `alembic revision --autogenerate` produce
# reversible migrations: without it, Postgres invents constraint names and
# downgrade() cannot find them again.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every table in the system.

    Alembic compares against ``Base.metadata``, so every model must be imported
    before autogenerate runs (see ``alembic/env.py``).
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Every table has a surrogate id and audit timestamps. See TICKET-005.

    ``id`` is a UUID generated by the database, so two processes can insert
    without coordinating. ``updated_at`` is maintained by the database too.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
