"""source domain schema

Revision ID: 8071e9ba07f7
Revises:
Create Date: 2026-09-22 00:30:54.095312

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "8071e9ba07f7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amendment",
        sa.Column("contract_ref", sa.String(length=100), nullable=False),
        sa.Column("amendment_number", sa.String(length=100), nullable=False),
        sa.Column("change_type", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("signed_date", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amendment")),
        sa.UniqueConstraint("source_system", "source_id", name="uq_amendment_source_natural_key"),
    )
    op.create_index("ix_amendment_contract_ref", "amendment", ["contract_ref"], unique=False)
    op.create_table(
        "amendment_term",
        sa.Column("amendment_ref", sa.String(length=100), nullable=False),
        sa.Column("term_type", sa.String(length=50), nullable=False),
        sa.Column("old_value", sa.String(length=255), nullable=True),
        sa.Column("new_value", sa.String(length=255), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amendment_term")),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_amendment_term_source_natural_key"
        ),
    )
    op.create_index(
        "ix_amendment_term_amendment_ref", "amendment_term", ["amendment_ref"], unique=False
    )
    op.create_table(
        "contract",
        sa.Column("customer_ref", sa.String(length=100), nullable=False),
        sa.Column("contract_number", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("signed_date", sa.Date(), nullable=True),
        sa.Column("term_months", sa.Integer(), nullable=True),
        sa.Column("renewal_type", sa.String(length=50), nullable=True),
        sa.Column("notice_period_days", sa.Integer(), nullable=True),
        sa.Column("billing_frequency", sa.String(length=50), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract")),
        sa.UniqueConstraint("source_system", "source_id", name="uq_contract_source_natural_key"),
    )
    op.create_index("ix_contract_contract_number", "contract", ["contract_number"], unique=False)
    op.create_index("ix_contract_customer_ref", "contract", ["customer_ref"], unique=False)
    op.create_table(
        "contract_clause",
        sa.Column("contract_ref", sa.String(length=100), nullable=False),
        sa.Column("clause_type", sa.String(length=50), nullable=False),
        sa.Column("clause_number", sa.String(length=50), nullable=True),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("tsv", postgresql.TSVECTOR(), nullable=True),
        sa.Column("embedding", Vector(dim=1536), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_clause")),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_contract_clause_source_natural_key"
        ),
    )
    op.create_index(
        "ix_contract_clause_clause_type", "contract_clause", ["clause_type"], unique=False
    )
    op.create_index(
        "ix_contract_clause_contract_ref", "contract_clause", ["contract_ref"], unique=False
    )
    op.create_table(
        "contract_term",
        sa.Column("contract_ref", sa.String(length=100), nullable=False),
        sa.Column("source_clause_ref", sa.String(length=100), nullable=True),
        sa.Column("term_type", sa.String(length=50), nullable=False),
        sa.Column("value_numeric", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("value_text", sa.String(length=255), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("extraction_method", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contract_term")),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_contract_term_source_natural_key"
        ),
    )
    op.create_index(
        "ix_contract_term_contract_ref", "contract_term", ["contract_ref"], unique=False
    )
    op.create_index("ix_contract_term_term_type", "contract_term", ["term_type"], unique=False)
    op.create_table(
        "credit_memo",
        sa.Column("customer_ref", sa.String(length=100), nullable=False),
        sa.Column("invoice_ref", sa.String(length=100), nullable=True),
        sa.Column("credit_memo_number", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=True),
        sa.Column("amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credit_memo")),
        sa.UniqueConstraint("source_system", "source_id", name="uq_credit_memo_source_natural_key"),
    )
    op.create_index("ix_credit_memo_customer_ref", "credit_memo", ["customer_ref"], unique=False)
    op.create_index("ix_credit_memo_invoice_ref", "credit_memo", ["invoice_ref"], unique=False)
    op.create_table(
        "crm_opportunity",
        sa.Column("customer_ref", sa.String(length=100), nullable=False),
        sa.Column("opportunity_ref", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("discount_pct", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("close_date", sa.Date(), nullable=True),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.Column("raw_payload", sa.JSON().with_variant(sa.JSON(), "postgresql"), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crm_opportunity")),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_crm_opportunity_source_natural_key"
        ),
    )
    op.create_index(
        "ix_crm_opportunity_customer_ref", "crm_opportunity", ["customer_ref"], unique=False
    )
    op.create_index(
        "ix_crm_opportunity_opportunity_ref", "crm_opportunity", ["opportunity_ref"], unique=False
    )
    op.create_table(
        "customer",
        sa.Column("customer_ref", sa.String(length=100), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("account_owner", sa.String(length=255), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer")),
        sa.UniqueConstraint("customer_ref", name=op.f("uq_customer_customer_ref")),
        sa.UniqueConstraint("source_system", "source_id", name="uq_customer_source_natural_key"),
    )
    op.create_table(
        "fx_rate",
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_rate")),
        sa.UniqueConstraint(
            "base_currency", "quote_currency", "as_of_date", name="uq_fx_rate_pair_as_of_date"
        ),
        sa.UniqueConstraint("source_system", "source_id", name="uq_fx_rate_source_natural_key"),
    )
    op.create_table(
        "implementation",
        sa.Column("customer_ref", sa.String(length=100), nullable=False),
        sa.Column("subscription_ref", sa.String(length=100), nullable=True),
        sa.Column("project_ref", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("go_live_date", sa.Date(), nullable=True),
        sa.Column("actual_activation_date", sa.Date(), nullable=True),
        sa.Column("onboarding_fee", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("services_delivered", sa.JSON(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_implementation")),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_implementation_source_natural_key"
        ),
    )
    op.create_index(
        "ix_implementation_customer_ref", "implementation", ["customer_ref"], unique=False
    )
    op.create_index(
        "ix_implementation_subscription_ref", "implementation", ["subscription_ref"], unique=False
    )
    op.create_table(
        "invoice",
        sa.Column("customer_ref", sa.String(length=100), nullable=False),
        sa.Column("invoice_number", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("subtotal", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("tax", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("total", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice")),
        sa.UniqueConstraint("source_system", "source_id", name="uq_invoice_source_natural_key"),
    )
    op.create_index("ix_invoice_customer_ref", "invoice", ["customer_ref"], unique=False)
    op.create_index("ix_invoice_invoice_number", "invoice", ["invoice_number"], unique=False)
    op.create_index("ix_invoice_period_start", "invoice", ["period_start"], unique=False)
    op.create_table(
        "invoice_line",
        sa.Column("invoice_ref", sa.String(length=100), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("product_ref", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("service_period_start", sa.Date(), nullable=True),
        sa.Column("service_period_end", sa.Date(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_line")),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_invoice_line_source_natural_key"
        ),
    )
    op.create_index("ix_invoice_line_invoice_ref", "invoice_line", ["invoice_ref"], unique=False)
    op.create_index("ix_invoice_line_product_ref", "invoice_line", ["product_ref"], unique=False)
    op.create_index(
        "ix_invoice_line_service_period_start",
        "invoice_line",
        ["service_period_start"],
        unique=False,
    )
    op.create_table(
        "product",
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=50), nullable=False),
        sa.Column("list_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("sku", name=op.f("uq_product_sku")),
        sa.UniqueConstraint("source_system", "source_id", name="uq_product_source_natural_key"),
    )
    op.create_table(
        "subscription",
        sa.Column("customer_ref", sa.String(length=100), nullable=False),
        sa.Column("contract_ref", sa.String(length=100), nullable=True),
        sa.Column("subscription_number", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("billing_frequency", sa.String(length=50), nullable=False),
        sa.Column("billing_anchor_date", sa.Date(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription")),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_subscription_source_natural_key"
        ),
    )
    op.create_index("ix_subscription_customer_ref", "subscription", ["customer_ref"], unique=False)
    op.create_index(
        "ix_subscription_subscription_number", "subscription", ["subscription_number"], unique=False
    )
    op.create_table(
        "subscription_line",
        sa.Column("subscription_ref", sa.String(length=100), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("product_ref", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_line")),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_subscription_line_source_natural_key"
        ),
    )
    op.create_index(
        "ix_subscription_line_is_current", "subscription_line", ["is_current"], unique=False
    )
    op.create_index(
        "ix_subscription_line_product_ref", "subscription_line", ["product_ref"], unique=False
    )
    op.create_index(
        "ix_subscription_line_subscription_ref",
        "subscription_line",
        ["subscription_ref"],
        unique=False,
    )
    op.create_table(
        "usage_snapshot",
        sa.Column("customer_ref", sa.String(length=100), nullable=False),
        sa.Column("product_ref", sa.String(length=100), nullable=False),
        sa.Column("metric", sa.String(length=50), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_snapshot")),
        sa.UniqueConstraint(
            "customer_ref",
            "product_ref",
            "metric",
            "period_start",
            name="uq_usage_snapshot_customer_product_metric_period",
        ),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_usage_snapshot_source_natural_key"
        ),
    )
    op.create_index(
        "ix_usage_snapshot_period_start", "usage_snapshot", ["period_start"], unique=False
    )
    op.create_table(
        "customer_alias",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("alias_name", sa.String(length=255), nullable=False),
        sa.Column("match_confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
            name=op.f("fk_customer_alias_customer_id_customer"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_alias")),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_customer_alias_source_natural_key"
        ),
    )
    op.create_index("ix_customer_alias_alias_name", "customer_alias", ["alias_name"], unique=False)
    op.create_index(
        "ix_customer_alias_customer_id", "customer_alias", ["customer_id"], unique=False
    )
    op.create_table(
        "pricing_rule",
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("rule_type", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("specificity", sa.Integer(), nullable=False),
        sa.Column("customer_ref", sa.String(length=100), nullable=True),
        sa.Column("min_quantity", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("max_quantity", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_pricing_rule_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_rule")),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_pricing_rule_source_natural_key"
        ),
    )
    op.create_index("ix_pricing_rule_customer_ref", "pricing_rule", ["customer_ref"], unique=False)
    op.create_index("ix_pricing_rule_product_id", "pricing_rule", ["product_id"], unique=False)
    op.create_table(
        "product_alias",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("alias_sku", sa.String(length=100), nullable=False),
        sa.Column("alias_source", sa.String(length=32), nullable=False),
        sa.Column("match_confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "source_system",
            sa.Enum(
                "contract",
                "crm",
                "implementation",
                "usage",
                "billing",
                name="source_system",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_product_alias_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_alias")),
        sa.UniqueConstraint(
            "source_system", "source_id", name="uq_product_alias_source_natural_key"
        ),
    )
    op.create_index("ix_product_alias_alias_sku", "product_alias", ["alias_sku"], unique=False)
    op.create_index("ix_product_alias_product_id", "product_alias", ["product_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_product_alias_product_id", table_name="product_alias")
    op.drop_index("ix_product_alias_alias_sku", table_name="product_alias")
    op.drop_table("product_alias")
    op.drop_index("ix_pricing_rule_product_id", table_name="pricing_rule")
    op.drop_index("ix_pricing_rule_customer_ref", table_name="pricing_rule")
    op.drop_table("pricing_rule")
    op.drop_index("ix_customer_alias_customer_id", table_name="customer_alias")
    op.drop_index("ix_customer_alias_alias_name", table_name="customer_alias")
    op.drop_table("customer_alias")
    op.drop_index("ix_usage_snapshot_period_start", table_name="usage_snapshot")
    op.drop_table("usage_snapshot")
    op.drop_index("ix_subscription_line_subscription_ref", table_name="subscription_line")
    op.drop_index("ix_subscription_line_product_ref", table_name="subscription_line")
    op.drop_index("ix_subscription_line_is_current", table_name="subscription_line")
    op.drop_table("subscription_line")
    op.drop_index("ix_subscription_subscription_number", table_name="subscription")
    op.drop_index("ix_subscription_customer_ref", table_name="subscription")
    op.drop_table("subscription")
    op.drop_table("product")
    op.drop_index("ix_invoice_line_service_period_start", table_name="invoice_line")
    op.drop_index("ix_invoice_line_product_ref", table_name="invoice_line")
    op.drop_index("ix_invoice_line_invoice_ref", table_name="invoice_line")
    op.drop_table("invoice_line")
    op.drop_index("ix_invoice_period_start", table_name="invoice")
    op.drop_index("ix_invoice_invoice_number", table_name="invoice")
    op.drop_index("ix_invoice_customer_ref", table_name="invoice")
    op.drop_table("invoice")
    op.drop_index("ix_implementation_subscription_ref", table_name="implementation")
    op.drop_index("ix_implementation_customer_ref", table_name="implementation")
    op.drop_table("implementation")
    op.drop_table("fx_rate")
    op.drop_table("customer")
    op.drop_index("ix_crm_opportunity_opportunity_ref", table_name="crm_opportunity")
    op.drop_index("ix_crm_opportunity_customer_ref", table_name="crm_opportunity")
    op.drop_table("crm_opportunity")
    op.drop_index("ix_credit_memo_invoice_ref", table_name="credit_memo")
    op.drop_index("ix_credit_memo_customer_ref", table_name="credit_memo")
    op.drop_table("credit_memo")
    op.drop_index("ix_contract_term_term_type", table_name="contract_term")
    op.drop_index("ix_contract_term_contract_ref", table_name="contract_term")
    op.drop_table("contract_term")
    op.drop_index("ix_contract_clause_contract_ref", table_name="contract_clause")
    op.drop_index("ix_contract_clause_clause_type", table_name="contract_clause")
    op.drop_table("contract_clause")
    op.drop_index("ix_contract_customer_ref", table_name="contract")
    op.drop_index("ix_contract_contract_number", table_name="contract")
    op.drop_table("contract")
    op.drop_index("ix_amendment_term_amendment_ref", table_name="amendment_term")
    op.drop_table("amendment_term")
    op.drop_index("ix_amendment_contract_ref", table_name="amendment")
    op.drop_table("amendment")
    # ### end Alembic commands ###
