"""derived case and ops schema

Revision ID: e0bf8ae51a4f
Revises: 8071e9ba07f7
Create Date: 2026-09-22 01:43:47.963682

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e0bf8ae51a4f'
down_revision: str | None = '8071e9ba07f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_exception',
    sa.Column('customer_ref', sa.String(length=100), nullable=False),
    sa.Column('subscription_line_ref', sa.String(length=100), nullable=True),
    sa.Column('product_ref', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Enum('free_pilot', 'approved_discount', 'grace_period', 'grandfathered_rate', 'contractual_cap', 'goodwill_credit', name='exception_reason', native_enum=False, length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approved_exception')),
    sa.UniqueConstraint('customer_ref', 'subscription_line_ref', 'reason', 'valid_from', name='uq_approved_exception_customer_line_reason_from')
    )
    op.create_index('ix_approved_exception_customer_ref', 'approved_exception', ['customer_ref'], unique=False)
    op.create_index('ix_approved_exception_reason', 'approved_exception', ['reason'], unique=False)
    op.create_index('ix_approved_exception_valid_from', 'approved_exception', ['valid_from'], unique=False)
    op.create_index('ix_approved_exception_valid_to', 'approved_exception', ['valid_to'], unique=False)
    op.create_table('audit_event',
    sa.Column('entity_table', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('insert', 'update', 'delete', 'status_change', 'approval', name='audit_action', native_enum=False, length=32), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_type', sa.Enum('system', 'human', 'agent', name='actor_type', native_enum=False, length=16), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index('ix_audit_event_actor', 'audit_event', ['actor'], unique=False)
    op.create_index('ix_audit_event_entity', 'audit_event', ['entity_table', 'entity_id'], unique=False)
    op.create_index('ix_audit_event_occurred_at', 'audit_event', ['occurred_at'], unique=False)
    op.create_table('billing_period',
    sa.Column('subscription_ref', sa.String(length=100), nullable=False),
    sa.Column('subscription_line_ref', sa.String(length=100), nullable=True),
    sa.Column('customer_ref', sa.String(length=100), nullable=False),
    sa.Column('product_ref', sa.String(length=100), nullable=True),
    sa.Column('period_index', sa.Integer(), nullable=False),
    sa.Column('period', postgresql.DATERANGE(), nullable=False),
    sa.Column('days_in_period', sa.Integer(), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('proration_factor', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_period')),
    sa.UniqueConstraint('subscription_ref', 'period_index', name='uq_billing_period_subscription_period_index')
    )
    op.create_index('ix_billing_period_customer_ref', 'billing_period', ['customer_ref'], unique=False)
    op.create_index('ix_billing_period_period', 'billing_period', ['period'], unique=False)
    op.create_index('ix_billing_period_period_index', 'billing_period', ['period_index'], unique=False)
    op.create_index('ix_billing_period_subscription_ref', 'billing_period', ['subscription_ref'], unique=False)
    op.create_table('case',
    sa.Column('case_key', sa.String(length=128), nullable=False),
    sa.Column('fingerprint_version', sa.Integer(), nullable=False),
    sa.Column('customer_ref', sa.String(length=100), nullable=False),
    sa.Column('subscription_line_ref', sa.String(length=100), nullable=True),
    sa.Column('product_ref', sa.String(length=100), nullable=True),
    sa.Column('leak_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'needs_review', 'confirmed', 'valid_exception', 'resolved', 'dismissed', name='case_status', native_enum=False, length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('delta_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence_band', sa.Enum('high', 'medium', 'low', name='confidence_band', native_enum=False, length=16), nullable=True),
    sa.Column('first_period_start', sa.Date(), nullable=True),
    sa.Column('last_period_end', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case')),
    sa.UniqueConstraint('case_key', name=op.f('uq_case_case_key'))
    )
    op.create_index('ix_case_customer_ref', 'case', ['customer_ref'], unique=False)
    op.create_index('ix_case_leak_type', 'case', ['leak_type'], unique=False)
    op.create_index('ix_case_status', 'case', ['status'], unique=False)
    op.create_table('change_event',
    sa.Column('customer_ref', sa.String(length=100), nullable=False),
    sa.Column('entity_table', sa.String(length=100), nullable=False),
    sa.Column('entity_ref', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('detected_by', sa.Enum('rule', 'model', 'human', name='change_detection_source', native_enum=False, length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_event'))
    )
    op.create_index('ix_change_event_customer_ref', 'change_event', ['customer_ref'], unique=False)
    op.create_index('ix_change_event_entity', 'change_event', ['entity_table', 'entity_ref'], unique=False)
    op.create_index('ix_change_event_observed_at', 'change_event', ['observed_at'], unique=False)
    op.create_table('entity_resolution_match',
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('left_system', sa.String(length=32), nullable=False),
    sa.Column('left_ref', sa.String(length=255), nullable=False),
    sa.Column('right_system', sa.String(length=32), nullable=False),
    sa.Column('right_ref', sa.String(length=255), nullable=False),
    sa.Column('method', sa.Enum('exact', 'normalised', 'fuzzy', 'domain', 'manual', name='match_method', native_enum=False, length=32), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('decision', sa.Enum('auto_matched', 'human_confirmed', 'human_rejected', name='match_decision', native_enum=False, length=32), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_resolution_match')),
    sa.UniqueConstraint('entity_type', 'left_system', 'left_ref', 'right_system', 'right_ref', name='uq_entity_resolution_match_pair')
    )
    op.create_index('ix_entity_resolution_match_decision', 'entity_resolution_match', ['decision'], unique=False)
    op.create_index('ix_entity_resolution_match_left', 'entity_resolution_match', ['left_system', 'left_ref'], unique=False)
    op.create_index('ix_entity_resolution_match_right', 'entity_resolution_match', ['right_system', 'right_ref'], unique=False)
    op.create_table('golden_label',
    sa.Column('scenario_id', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('customer_ref', sa.String(length=100), nullable=False),
    sa.Column('leak_type', sa.String(length=100), nullable=False),
    sa.Column('subscription_line_ref', sa.String(length=100), nullable=True),
    sa.Column('product_ref', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('expected_delta_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('expected_period_count', sa.Integer(), nullable=True),
    sa.Column('is_benign', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_golden_label'))
    )
    op.create_index('ix_golden_label_customer_ref', 'golden_label', ['customer_ref'], unique=False)
    op.create_index('ix_golden_label_leak_type', 'golden_label', ['leak_type'], unique=False)
    op.create_index('ix_golden_label_scenario_id', 'golden_label', ['scenario_id'], unique=False)
    op.create_table('reconciliation_result',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('customer_ref', sa.String(length=100), nullable=False),
    sa.Column('line_ref', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('check_code', sa.String(length=100), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('delta_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_result')),
    sa.UniqueConstraint('run_id', 'customer_ref', 'line_ref', 'period_start', 'check_code', name='uq_reconciliation_result_run_customer_line_period_check')
    )
    op.create_index('ix_reconciliation_result_check_code', 'reconciliation_result', ['check_code'], unique=False)
    op.create_index('ix_reconciliation_result_customer_ref', 'reconciliation_result', ['customer_ref'], unique=False)
    op.create_index('ix_reconciliation_result_run_id', 'reconciliation_result', ['run_id'], unique=False)
    op.create_table('reconciliation_run',
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='run_status', native_enum=False, length=32), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('scenario_id', sa.String(length=100), nullable=True),
    sa.Column('dataset_version', sa.String(length=100), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('engine_version', sa.String(length=64), nullable=True),
    sa.Column('config_hash', sa.String(length=128), nullable=True),
    sa.Column('git_sha', sa.String(length=64), nullable=True),
    sa.Column('customers_scanned', sa.Integer(), nullable=False),
    sa.Column('checks_executed', sa.Integer(), nullable=False),
    sa.Column('results_written', sa.Integer(), nullable=False),
    sa.Column('cases_opened', sa.Integer(), nullable=False),
    sa.Column('cases_updated', sa.Integer(), nullable=False),
    sa.Column('total_delta_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_run'))
    )
    op.create_index('ix_reconciliation_run_as_of_date', 'reconciliation_run', ['as_of_date'], unique=False)
    op.create_index('ix_reconciliation_run_scenario_id', 'reconciliation_run', ['scenario_id'], unique=False)
    op.create_index('ix_reconciliation_run_status', 'reconciliation_run', ['status'], unique=False)
    op.create_table('case_outcome',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('outcome_type', sa.Enum('recovered', 'partially_recovered', 'written_off', 'false_positive', 'accepted_exception', name='outcome_type', native_enum=False, length=32), nullable=False),
    sa.Column('recovered_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('written_off_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.Date(), nullable=True),
    sa.Column('approved_exception_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_exception_id'], ['approved_exception.id'], name=op.f('fk_case_outcome_approved_exception_id_approved_exception'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_case_outcome_case_id_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_outcome')),
    sa.UniqueConstraint('case_id', name=op.f('uq_case_outcome_case_id'))
    )
    op.create_index('ix_case_outcome_outcome_type', 'case_outcome', ['outcome_type'], unique=False)
    op.create_index('ix_case_outcome_reason_code', 'case_outcome', ['reason_code'], unique=False)
    op.create_table('case_period',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('delta_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_case_period_case_id_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_period'))
    )
    op.create_index('ix_case_period_case_id', 'case_period', ['case_id'], unique=False)
    op.create_index('ix_case_period_start', 'case_period', ['period_start'], unique=False)
    op.create_table('eval_run',
    sa.Column('suite', sa.Enum('retrieval', 'extraction', 'detection', 'case_clustering', 'confidence', 'end_to_end', name='eval_suite', native_enum=False, length=32), nullable=False),
    sa.Column('git_sha', sa.String(length=64), nullable=True),
    sa.Column('dataset_version', sa.String(length=100), nullable=True),
    sa.Column('scenario_id', sa.String(length=100), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('recall', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('f1', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_run.id'], name=op.f('fk_eval_run_run_id_reconciliation_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_run'))
    )
    op.create_index('ix_eval_run_git_sha', 'eval_run', ['git_sha'], unique=False)
    op.create_index('ix_eval_run_suite', 'eval_run', ['suite'], unique=False)
    op.create_table('evidence',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('citation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_evidence_case_id_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index('ix_evidence_case_id', 'evidence', ['case_id'], unique=False)
    op.create_index('ix_evidence_source', 'evidence', ['source_table', 'source_id'], unique=False)
    op.create_table('investigation_run',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('max_steps', sa.Integer(), nullable=True),
    sa.Column('steps_used', sa.Integer(), nullable=True),
    sa.Column('max_tool_calls', sa.Integer(), nullable=True),
    sa.Column('tool_calls_used', sa.Integer(), nullable=True),
    sa.Column('token_budget', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('terminal_reason', sa.Enum('completed', 'budget_exhausted', 'max_steps_reached', 'low_confidence', 'verifier_rejected', 'error', name='terminal_reason', native_enum=False, length=32), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_investigation_run_case_id_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_run')),
    sa.UniqueConstraint('case_id', 'attempt', name='uq_investigation_run_case_attempt')
    )
    op.create_index('ix_investigation_run_case_id', 'investigation_run', ['case_id'], unique=False)
    op.create_index('ix_investigation_run_terminal_reason', 'investigation_run', ['terminal_reason'], unique=False)
    op.create_table('job',
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'cancelled', name='job_status', native_enum=False, length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=255), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_job_case_id_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index('ix_job_case_id', 'job', ['case_id'], unique=False)
    op.create_index('ix_job_dedupe_key', 'job', ['dedupe_key'], unique=True)
    op.create_index('ix_job_run_after', 'job', ['run_after'], unique=False)
    op.create_index('ix_job_status', 'job', ['status'], unique=False)
    op.create_index('ix_job_type', 'job', ['job_type'], unique=False)
    op.create_table('qa_message',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('question', 'answer', name='qa_role', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('refused', sa.Boolean(), nullable=False),
    sa.Column('refusal_reason', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_qa_message_case_id_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_message'))
    )
    op.create_index('ix_qa_message_case_id', 'qa_message', ['case_id'], unique=False)
    op.create_table('recommendation',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('target_system', sa.String(length=32), nullable=False),
    sa.Column('target_record_ref', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('approval_state', sa.Enum('proposed', 'approved', 'rejected', 'executed', name='approval_state', native_enum=False, length=32), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_recommendation_case_id_case'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation'))
    )
    op.create_index('ix_recommendation_approval_state', 'recommendation', ['approval_state'], unique=False)
    op.create_index('ix_recommendation_case_id', 'recommendation', ['case_id'], unique=False)
    op.create_table('agent_trace_step',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('plan', 'retrieve', 'inspect', 'compute', 'verify', 'report', name='trace_phase', native_enum=False, length=32), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_args', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['investigation_run.id'], name=op.f('fk_agent_trace_step_run_id_investigation_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_trace_step')),
    sa.UniqueConstraint('run_id', 'step_index', name='uq_agent_trace_step_run_step')
    )
    op.create_index('ix_agent_trace_step_phase', 'agent_trace_step', ['run_id', 'phase'], unique=False)
    op.create_index('ix_agent_trace_step_run_id', 'agent_trace_step', ['run_id'], unique=False)
    op.create_table('eval_result',
    sa.Column('eval_run_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=False),
    sa.Column('item_ref', sa.String(length=255), nullable=True),
    sa.Column('golden_label_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('expected', sa.JSON(), nullable=True),
    sa.Column('actual', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('failure_mode', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_eval_result_case_id_case'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_run.id'], name=op.f('fk_eval_result_eval_run_id_eval_run'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['golden_label_id'], ['golden_label.id'], name=op.f('fk_eval_result_golden_label_id_golden_label'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_result'))
    )
    op.create_index('ix_eval_result_eval_run_id', 'eval_result', ['eval_run_id'], unique=False)
    op.create_index('ix_eval_result_failure_mode', 'eval_result', ['failure_mode'], unique=False)
    op.create_index('ix_eval_result_item', 'eval_result', ['item_type', 'item_ref'], unique=False)
    op.create_index('ix_eval_result_passed', 'eval_result', ['passed'], unique=False)
    op.create_table('investigation_report',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('root_cause_category', sa.String(length=100), nullable=True),
    sa.Column('proposed_correction', sa.Text(), nullable=True),
    sa.Column('proposed_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('qualitative_factor', sa.String(length=255), nullable=True),
    sa.Column('qualitative_note', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_investigation_report_case_id_case'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['investigation_run.id'], name=op.f('fk_investigation_report_run_id_investigation_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_report')),
    sa.UniqueConstraint('case_id', 'version', name='uq_investigation_report_case_version')
    )
    op.create_index('ix_investigation_report_case_id', 'investigation_report', ['case_id'], unique=False)
    op.create_index('ix_investigation_report_root_cause', 'investigation_report', ['root_cause_category'], unique=False)
    op.create_table('llm_call',
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('succeeded', 'failed', 'timeout', 'mock', name='llm_call_status', native_enum=False, length=32), nullable=False),
    sa.Column('prompt_hash', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('trace_step_id', sa.Uuid(), nullable=True),
    sa.Column('mocked', sa.Boolean(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_llm_call_case_id_case'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['investigation_run.id'], name=op.f('fk_llm_call_run_id_investigation_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trace_step_id'], ['agent_trace_step.id'], name=op.f('fk_llm_call_trace_step_id_agent_trace_step'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_call'))
    )
    op.create_index('ix_llm_call_case_id', 'llm_call', ['case_id'], unique=False)
    op.create_index('ix_llm_call_model', 'llm_call', ['model'], unique=False)
    op.create_index('ix_llm_call_purpose', 'llm_call', ['purpose'], unique=False)
    op.create_index('ix_llm_call_run_id', 'llm_call', ['run_id'], unique=False)
    op.create_index('ix_contract_clause_embedding', 'contract_clause', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_contract_clause_tsv', 'contract_clause', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contract_clause_tsv', table_name='contract_clause', postgresql_using='gin')
    op.drop_index('ix_contract_clause_embedding', table_name='contract_clause', postgresql_using='hnsw', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_llm_call_run_id', table_name='llm_call')
    op.drop_index('ix_llm_call_purpose', table_name='llm_call')
    op.drop_index('ix_llm_call_model', table_name='llm_call')
    op.drop_index('ix_llm_call_case_id', table_name='llm_call')
    op.drop_table('llm_call')
    op.drop_index('ix_investigation_report_root_cause', table_name='investigation_report')
    op.drop_index('ix_investigation_report_case_id', table_name='investigation_report')
    op.drop_table('investigation_report')
    op.drop_index('ix_eval_result_passed', table_name='eval_result')
    op.drop_index('ix_eval_result_item', table_name='eval_result')
    op.drop_index('ix_eval_result_failure_mode', table_name='eval_result')
    op.drop_index('ix_eval_result_eval_run_id', table_name='eval_result')
    op.drop_table('eval_result')
    op.drop_index('ix_agent_trace_step_run_id', table_name='agent_trace_step')
    op.drop_index('ix_agent_trace_step_phase', table_name='agent_trace_step')
    op.drop_table('agent_trace_step')
    op.drop_index('ix_recommendation_case_id', table_name='recommendation')
    op.drop_index('ix_recommendation_approval_state', table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index('ix_qa_message_case_id', table_name='qa_message')
    op.drop_table('qa_message')
    op.drop_index('ix_job_type', table_name='job')
    op.drop_index('ix_job_status', table_name='job')
    op.drop_index('ix_job_run_after', table_name='job')
    op.drop_index('ix_job_dedupe_key', table_name='job')
    op.drop_index('ix_job_case_id', table_name='job')
    op.drop_table('job')
    op.drop_index('ix_investigation_run_terminal_reason', table_name='investigation_run')
    op.drop_index('ix_investigation_run_case_id', table_name='investigation_run')
    op.drop_table('investigation_run')
    op.drop_index('ix_evidence_source', table_name='evidence')
    op.drop_index('ix_evidence_case_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_eval_run_suite', table_name='eval_run')
    op.drop_index('ix_eval_run_git_sha', table_name='eval_run')
    op.drop_table('eval_run')
    op.drop_index('ix_case_period_start', table_name='case_period')
    op.drop_index('ix_case_period_case_id', table_name='case_period')
    op.drop_table('case_period')
    op.drop_index('ix_case_outcome_reason_code', table_name='case_outcome')
    op.drop_index('ix_case_outcome_outcome_type', table_name='case_outcome')
    op.drop_table('case_outcome')
    op.drop_index('ix_reconciliation_run_status', table_name='reconciliation_run')
    op.drop_index('ix_reconciliation_run_scenario_id', table_name='reconciliation_run')
    op.drop_index('ix_reconciliation_run_as_of_date', table_name='reconciliation_run')
    op.drop_table('reconciliation_run')
    op.drop_index('ix_reconciliation_result_run_id', table_name='reconciliation_result')
    op.drop_index('ix_reconciliation_result_customer_ref', table_name='reconciliation_result')
    op.drop_index('ix_reconciliation_result_check_code', table_name='reconciliation_result')
    op.drop_table('reconciliation_result')
    op.drop_index('ix_golden_label_scenario_id', table_name='golden_label')
    op.drop_index('ix_golden_label_leak_type', table_name='golden_label')
    op.drop_index('ix_golden_label_customer_ref', table_name='golden_label')
    op.drop_table('golden_label')
    op.drop_index('ix_entity_resolution_match_right', table_name='entity_resolution_match')
    op.drop_index('ix_entity_resolution_match_left', table_name='entity_resolution_match')
    op.drop_index('ix_entity_resolution_match_decision', table_name='entity_resolution_match')
    op.drop_table('entity_resolution_match')
    op.drop_index('ix_change_event_observed_at', table_name='change_event')
    op.drop_index('ix_change_event_entity', table_name='change_event')
    op.drop_index('ix_change_event_customer_ref', table_name='change_event')
    op.drop_table('change_event')
    op.drop_index('ix_case_status', table_name='case')
    op.drop_index('ix_case_leak_type', table_name='case')
    op.drop_index('ix_case_customer_ref', table_name='case')
    op.drop_table('case')
    op.drop_index('ix_billing_period_subscription_ref', table_name='billing_period')
    op.drop_index('ix_billing_period_period_index', table_name='billing_period')
    op.drop_index('ix_billing_period_period', table_name='billing_period')
    op.drop_index('ix_billing_period_customer_ref', table_name='billing_period')
    op.drop_table('billing_period')
    op.drop_index('ix_audit_event_occurred_at', table_name='audit_event')
    op.drop_index('ix_audit_event_entity', table_name='audit_event')
    op.drop_index('ix_audit_event_actor', table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index('ix_approved_exception_valid_to', table_name='approved_exception')
    op.drop_index('ix_approved_exception_valid_from', table_name='approved_exception')
    op.drop_index('ix_approved_exception_reason', table_name='approved_exception')
    op.drop_index('ix_approved_exception_customer_ref', table_name='approved_exception')
    op.drop_table('approved_exception')
    # ### end Alembic commands ###
